spring.application.name=oauth-demo
server.port=8080

spring.security.oauth2.client.registration.google.client-id=264719369719-889jgu1nqt59vmmdnffos9d12usflqn4.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG
logging.level.com.example.oauthdemo=DEBUG